### ISSUE TITLE
Add icon for admin bar

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/l10n_server#15]
The admin bar item "Localization server" is displayed without icon.

<img src="https://user-images.githubusercontent.com/14188307/232505803-a9a5ac65-9297-40e7-8bda-2195eb5dc0a4.png" width="480">

Let's look for a good icon and add it to the module.

**Comment by olafgrabienski** [comment]
> Let's look for a good icon ...

Maybe a globe symbol? &#x1F310;

**Comment by olafgrabienski** [comment]
Here is a mockup with a globe icon. What do you think of it, @argiepiano ?

<img src="https://user-images.githubusercontent.com/14188307/232520312-860ab74c-1291-4b5f-97fc-0daff092701f.png" width="480">

**Comment by argiepiano** [comment]
Looks great! Do you think you can submit a PR?

**Comment by olafgrabienski** [comment]
> Do you think you can submit a PR?

Not sure, a PR with various new files (I'm using the Github UI) is new for me. I can however provide the CSS snippet and the PNG icon.

CSS snippet:

```
#admin-bar #admin-bar-menu > li > .dropdown > li > a.admin-l10n-server {
  background: transparent url(PATH-TO/globe--white--64.png) 5% center no-repeat;
  background-size: 16px;
}
```

PNG icon: https://user-images.githubusercontent.com/14188307/232548204-14873723-6892-4e6a-b181-df2034714c76.png
  (To see the image, make sure to place it on a dark background.)

If you prefer a PR, how should I name and where should I put the CSS file and the image?

**Comment by argiepiano** [comment]
Added and merged! Thanks, @olafgrabienski!
