### ISSUE TITLE
Store `l10n_cron_stats` in the state system

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/l10n_server#21]
There is a value, `l10n_cron_stats` in the `l10n_community.settings.json` file that looks like a timestamp that gets updated regularly. If so, this should be stored in the state system instead of config. If it is not a configuration option that needs to be deployed across sites, and is instead a reflection of the state of an individual site, then it should live in the database for that site.  When stored in config, and when config is versioned, this shows up as a modified file that needs to be committed often.

**Comment by argiepiano** [comment]
Agreed. WIll fix tonight.
